import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def send_email_notification(analysis_result, pipeline_name, stage_name, build_number):
    """
    Sends a formatted HTML email notification using SMTP.

    Args:
        analysis_result (dict): The JSON result from the AI analysis.
        pipeline_name (str): Name of the pipeline.
        stage_name (str): Name of the failing stage.
        build_number (str): The Jenkins build number.

    Returns:
        bool: True if email was sent successfully, False otherwise.
    """
    # Read configuration from environment variables
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = os.getenv("SMTP_PORT", "587")
    smtp_user = os.getenv("SMTP_USERNAME")
    smtp_pass = os.getenv("SMTP_PASSWORD")
    email_from = os.getenv("EMAIL_FROM")
    email_to = os.getenv("EMAIL_TO")

    # Validate that all required credentials are provided
    if not all([smtp_host, smtp_user, smtp_pass, email_from, email_to]):
        print("Error: Missing SMTP configuration in environment variables.")
        return False

    # Severity badge colors
    colors = {
        "high": "#FF4C4C",    # Bright Red
        "medium": "#FFA500",  # Orange
        "low": "#90EE90"      # Light Green
    }
    severity = analysis_result.get("severity", "medium").lower()
    badge_color = colors.get(severity, "#CCCCCC")

    # Email Subject
    severity_icon = "[HIGH]" if severity == "high" else "[MED]" if severity == "medium" else "[LOW]"
    subject = f"{severity_icon} [Novapay CI Doctor] Build #{build_number} Failed - {stage_name} stage"

    # Pre-process fix suggestion (backslash can't go inside f-string {})
    fix_suggestion_text = analysis_result.get("fix_suggestion", "No fix suggested.")
    fix_suggestion_html = fix_suggestion_text.replace('\n', '<br>')

    # HTML Body construction for a professional look
    html_content = f"""
    <html style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
    <body style="color: #333; background-color: #f4f7f6; padding: 20px;">
        <div style="max-width: 650px; margin: auto; background: white; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
            <div style="background-color: #2c3e50; color: white; padding: 20px; text-align: center;">
                <h2 style="margin: 0;">CI Failure Analysis Report</h2>
            </div>
            <div style="padding: 20px;">
                <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                    <tr>
                        <td style="padding: 8px 0; color: #7f8c8d; width: 120px;"><strong>Pipeline:</strong></td>
                        <td style="padding: 8px 0;">{pipeline_name}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0; color: #7f8c8d;"><strong>Stage:</strong></td>
                        <td style="padding: 8px 0;">{stage_name}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0; color: #7f8c8d;"><strong>Build #:</strong></td>
                        <td style="padding: 8px 0;">#{build_number}</td>
                    </tr>
                </table>

                <div style="margin-bottom: 20px; text-align: center;">
                    <span style="background-color: {badge_color}; color: white; padding: 6px 12px; border-radius: 4px; font-weight: bold; text-transform: uppercase; font-size: 12px;">
                        {severity} Severity
                    </span>
                    <span style="margin-left: 10px; background-color: #eee; color: #666; padding: 6px 12px; border-radius: 4px; font-size: 12px;">
                        Category: {analysis_result.get("category", "N/A")}
                    </span>
                </div>

                <h3 style="color: #e74c3c; border-bottom: 2px solid #e74c3c; padding-bottom: 5px;">Root Cause</h3>
                <p style="background-color: #fff5f5; padding: 15px; border-left: 4px solid #e74c3c; color: #444;">
                    {analysis_result.get("root_cause", "No root cause identified.")}
                </p>

                <h3 style="color: #2ecc71; border-bottom: 2px solid #2ecc71; padding-bottom: 5px;">Suggested Fix</h3>
                <div style="background-color: #f0fff4; padding: 15px; border-left: 4px solid #2ecc71; color: #444; line-height: 1.6;">
                    {fix_suggestion_html}
                </div>

                <div style="margin-top: 30px; text-align: center; font-size: 11px; color: #999;">
                    AI Confidence: {analysis_result.get("confidence", "N/A")} | Generated by Novapay CI Doctor
                </div>
            </div>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg["From"] = email_from
    msg["To"] = email_to
    msg["Subject"] = subject
    msg.attach(MIMEText(html_content, "html"))

    # Retry logic: 2 attempts for temporary SMTP issues
    max_attempts = 2
    for attempt in range(max_attempts):
        try:
            with smtplib.SMTP(smtp_host, int(smtp_port)) as server:
                server.starttls()  # Enable encryption
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)
                print(f"Email notification sent successfully to {email_to}")
                return True
        except Exception as e:
            print(f"SMTP Attempt {attempt+1} failed: {str(e)}")
            if attempt == max_attempts - 1:
                print("Failed to send email after maximum attempts.")
                return False